import '@/assets/styles/styles.scss';
import { Providers } from '@/stores/provider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// eslint-disable-next-line no-undef
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <header>header</header>
        <main>
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  );
}
